### ISSUE TITLE
又一个PHP博客站点 - 网上冲浪

### ISSUE THREAD

**Issue by 53chonglang** [53chonglang/53chonglang#1]
https://www.53chonglang.com/index/article/1 

 这是一个使用PHP语言和MySQL数据库开发的个人博客系统，安装方式简单易用，你也想架设一个属于自己的博客网站吗？

**Comment by 53chonglang** [comment]
欢迎测试！

**Comment by nsczx** [comment]
<script>alert(1)</script>
